require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AssignsController do

  describe "POST create" do
    describe "with valid badge and existent user" do
      before do
        controller.stub!(:ensure_authenticated_to_facebook).and_return(false)
        controller.stub!(:current_user).and_return(mock_user(:confirmed? => true))
      end

      it "assigns a adds the badge to user" do
        u = User.create(:facebook_id => 123)
        b = Badge.create(:name => 'Test Badge', :picture_url => 'test')
        post :create, :fb_user_id => u.facebook_id, :badge_id => b.id, :format => :json
        u.should have_exactly(1).badges
      end
    end

    describe "with valid badge and new user" do
      before do
        controller.stub!(:ensure_authenticated_to_facebook).and_return(false)
        controller.stub!(:current_user).and_return(mock_user(:confirmed? => true))
      end

      it "assigns a adds the badge to user" do
        b = Badge.create(:name => 'Test Badge', :picture_url => 'test')
        post :create, :fb_user_id => 123, :badge_id => b.id, :format => :json
        User.find_by_facebook_id(123).should have_exactly(1).badges
      end
    end

    describe "with invalid badge and new user" do
      before do
        controller.stub!(:ensure_authenticated_to_facebook).and_return(false)
        controller.stub!(:current_user).and_return(mock_user(:confirmed? => true))
      end

      it "assigns a adds the badge to user" do
        post :create, :fb_user_id => 123, :badge_id => 123, :format => :json
        User.find_by_facebook_id(123).should have_exactly(0).badges
      end
    end

    describe "with no authorization" do
      before do
        controller.stub!(:ensure_authenticated_to_facebook).and_return(false)
        controller.stub!(:current_user).and_return(mock_user(:confirmed? => false))
      end

      it "redirects" do
        b = Badge.create(:name => 'Test Badge', :picture_url => 'test')
        post :create, :fb_user_id => 123, :badge_id => b.id, :format => :json
        response.should be_redirect
      end
    end
  end

end
